### ISSUE TITLE
invalid syntax on pip when building

### ISSUE THREAD

**Issue by MarcinWieczorek** [Wildsong/docker-ubuntu-server#1]
```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/47/ca/f0d790b6e18b3a6f3bd5e80c2ee4edbb5807286c21cdd0862ca933f751dd/pip-21.1.3-py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-21.1.3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 12, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/entrypoints.py", line 4, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
The command '/bin/sh -c pip3 install --upgrade pip && pip3 install requests' returned a non-zero code: 1
```

**Comment by bwilsoncc** [comment]
I did not try to troubleshoot that error but the entire image was outdated so I updated it to the latest Ubuntu LTS that is in the Esri list, 20.0.4.

**Comment by MarcinWieczorek** [comment]
That's what I did too and it built, but could not test the whole setup yet. Thanks.
